recipes:
    global:
        - dotfiles::gitconfig
        - dotfiles::vim

attributes:
    homebrewalt:
        apps:
            - git
            - scala
            - sbt
            - boot2docker
            - git-extras
            - findutils
            - gnu-sed
            - heroku-toolbelt
            - maven
            - tig
            - mercurial
        cask_apps:
            - intellij-idea
            - visualvm
            - java
            - vagrant
            - virtualbox
            - macvim
